// <auto-generated />
namespace ePrevoz.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zahtjevZaPrevoz_dodata_Kolicina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zahtjevZaPrevoz_dodata_Kolicina));
        
        string IMigrationMetadata.Id
        {
            get { return "201707140728404_zahtjevZaPrevoz_dodata_Kolicina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
